# Generated by Django 6.0.4 on 2026-07-06 08:43

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.text
import netbox.models.deletion
import netbox_backupjobs.models.backupjobs
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('ipam', '0089_default_ordering_indexes'),
        ('virtualization', '0056_virtualmachine_render_config_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('jobtype', models.CharField(blank=True, max_length=50)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='enabled', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('job_creation_time', models.DateTimeField(blank=True, null=True)),
                ('backup_server_name', models.CharField(blank=True, max_length=255)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('Algorithm', models.CharField(default='incremental', max_length=50)),
                ('EnableDeduplication', models.CharField(default='false', max_length=50)),
                ('StorageEncryptionEnabled', models.CharField(default='false', max_length=50)),
                ('RetainDaysToKeep', models.CharField(blank=True, max_length=50)),
                ('RetainCycles', models.CharField(blank=True, max_length=50)),
                ('EnableDeletedVmDataRetention', models.CharField(default='false', max_length=50)),
                ('RetainDaysToKeepDeletedVmData', models.CharField(blank=True, max_length=50)),
                ('TransformFullToSyntethic', models.CharField(default='false', max_length=50)),
                ('TransformToSyntheticFull', models.CharField(default='false', max_length=50)),
                ('TransformToSyntethicKind', models.CharField(default='daily', max_length=50)),
                ('TransformToSyntheticDays', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=netbox_backupjobs.models.backupjobs.default_synthetic_days)),
                ('SyntheticFullDayNumberInMonth', models.CharField(default='first', max_length=50)),
                ('SyntheticFullDayOfWeek', models.CharField(default='sunday', max_length=50)),
                ('TransformToSyntethicMonthly', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=netbox_backupjobs.models.backupjobs.default_synthetic_months)),
                ('EnableFullBackup', models.CharField(default='false', max_length=50)),
                ('FullBackupScheduleKind', models.CharField(default='daily', max_length=50)),
                ('FullBackupDays', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=netbox_backupjobs.models.backupjobs.default_full_backup_days)),
                ('FullBackupDayNumberInMonth', models.CharField(default='first', max_length=50)),
                ('FullBackupDayOfWeek', models.CharField(default='sunday', max_length=50)),
                ('FullBackupMonths', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=netbox_backupjobs.models.backupjobs.default_full_backup_months)),
                ('EnableGFS', models.CharField(default='false', max_length=50)),
                ('WeeklyEnabled', models.CharField(default='false', max_length=50)),
                ('WeeklyKeepBackupsFor', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('WeeklyKeepBackupsOnDayOfWeek', models.CharField(default='sunday', max_length=50)),
                ('MonthlyEnabled', models.CharField(default='false', max_length=50)),
                ('MonthlyKeepBackupsFor', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('MonthlyKeepBackupsWeekOfMonth', models.CharField(default='first', max_length=50)),
                ('YearlyEnabled', models.CharField(default='false', max_length=50)),
                ('YearlyKeepBackupsFor', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('YearlyKeepBackupsOnMonthOfYear', models.CharField(default='january', max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('backup_server_ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_jobs', to='ipam.ipaddress')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('virtual_machines', models.ManyToManyField(blank=True, related_name='backup_jobs', to='virtualization.virtualmachine')),
            ],
            options={
                'verbose_name': 'BackupJob',
                'verbose_name_plural': 'Veeam BackupJobs',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='netbox_backupjobs_backupjob_unique_name', violation_error_message="The BackupJob 'Name' must be unique.")],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
