# Generated by Django 6.0.4 on 2026-06-29 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0001_initial'),
        ('virtualization', '0056_virtualmachine_render_config_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='virtual_machines',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_jobs', to='virtualization.virtualmachine'),
        ),
    ]
