# Generated by Django 6.0.4 on 2026-07-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='LastBackupEndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='LastBackupResult',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
