# Generated by Django 6.0.4 on 2026-06-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0002_backupjob_virtual_machines'),
        ('virtualization', '0056_virtualmachine_render_config_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupjob',
            name='virtual_machines',
        ),
        migrations.AddField(
            model_name='backupjob',
            name='virtual_machines',
            field=models.ManyToManyField(blank=True, related_name='backup_jobs', to='virtualization.virtualmachine'),
        ),
    ]
