# Generated by Django 6.0.4 on 2026-07-06 14:21

import django.contrib.postgres.fields
import netbox_backupjobs.models.backupjobs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0002_backupjob_lastbackupendtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='RunAutomatically',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='ScheduleDailyDays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=netbox_backupjobs.models.backupjobs.default_schedule_daily_days),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='ScheduleDailyEnabled',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='ScheduleDailyKind',
            field=models.CharField(blank=True, default='everyday', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='ScheduleDailyTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='ScheduleMonthlyDayNumberInMonth',
            field=models.CharField(blank=True, default='fourth', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='ScheduleMonthlyDayOfWeek',
            field=models.CharField(blank=True, default='tuesday', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='ScheduleMonthlyEnabled',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='ScheduleMonthlyMonths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=netbox_backupjobs.models.backupjobs.default_schedule_monthly_months),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='ScheduleMonthlyTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='SchedulePeriodicallyEnabled',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='SchedulePeriodicallyEvery',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='SchedulePeriodicallyUnit',
            field=models.CharField(blank=True, default='hours', max_length=50),
        ),
    ]
