# Generated by Django 6.0.4 on 2026-06-30 07:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0003_remove_backupjob_virtual_machines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='Algorithm',
            field=models.CharField(default='incremental', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='EnableDeduplication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='EnableDeletedVmDataRetention',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='RetainCycles',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='RetainDaysToKeep',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='RetainDaysToKeepDeletedVmData',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='StorageEncryptionEnabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='SyntheticFullDayNumberInMonth',
            field=models.CharField(default='first', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='SyntheticFullDayOfWeek',
            field=models.CharField(default='sunday', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='TransformFullToSyntethic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='TransformToSyntethicKind',
            field=models.CharField(default='daily', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='TransformToSyntethicMonthly',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='TransformToSyntheticDays',
            field=models.CharField(default='monday', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='TransformToSyntheticFull',
            field=models.BooleanField(default=False),
        ),
    ]
