# Generated by Django 6.0.4 on 2026-07-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0003_backupjob_runautomatically_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='AfterJobEnabled',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='AfterJobName',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
