# Generated by Django 6.0.4 on 2026-07-06 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0004_backupjob_afterjobenabled_backupjob_afterjobname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupjob',
            name='AfterJobName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preceding_jobs', to='netbox_backupjobs.backupjob'),
        ),
    ]
