# Generated by Django 6.0.4 on 2026-06-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0004_backupjob_algorithm_backupjob_enablededuplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupjob',
            name='EnableDeduplication',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='EnableDeletedVmDataRetention',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='StorageEncryptionEnabled',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='TransformToSyntethicMonthly',
            field=models.CharField(blank=True, default='january', max_length=50),
        ),
    ]
