# Generated by Django 6.0.4 on 2026-06-30 08:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0005_alter_backupjob_enablededuplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupjob',
            name='TransformToSyntethicMonthly',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list),
        ),
    ]
