# Generated by Django 6.0.4 on 2026-07-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0005_alter_backupjob_afterjobname'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='ScheduleMonthlyDayOfMonth',
            field=models.CharField(blank=True, default='1', max_length=50),
        ),
    ]
