# Generated by Django 6.0.4 on 2026-06-30 08:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0006_alter_backupjob_transformtosyntethicmonthly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupjob',
            name='TransformFullToSyntethic',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='TransformToSyntheticDays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='TransformToSyntheticFull',
            field=models.CharField(default='false', max_length=50),
        ),
    ]
