# Generated by Django 6.0.4 on 2026-07-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0006_backupjob_schedulemonthlydayofmonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupjob',
            name='ScheduleMonthlyDayNumberInMonth',
            field=models.CharField(blank=True, default='first', max_length=50),
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='ScheduleMonthlyDayOfWeek',
            field=models.CharField(blank=True, default='saturday', max_length=50),
        ),
    ]
