# Generated by Django 6.0.4 on 2026-07-07 09:23

import django.contrib.postgres.fields
import netbox_backupjobs.models.backupjobs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0007_alter_backupjob_schedulemonthlydaynumberinmonth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='SchedulePeriodicallyFridaySchema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupjobs.default_schedule_all_hours),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='SchedulePeriodicallyMondaySchema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupjobs.default_schedule_all_hours),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='SchedulePeriodicallySaturdaySchema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupjobs.default_schedule_all_hours),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='SchedulePeriodicallySundaySchema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupjobs.default_schedule_all_hours),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='SchedulePeriodicallyThursdaySchema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupjobs.default_schedule_all_hours),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='SchedulePeriodicallyTuesdaySchema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupjobs.default_schedule_all_hours),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='SchedulePeriodicallyWednesdaySchema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupjobs.default_schedule_all_hours),
        ),
    ]
