# Generated by Django 6.0.4 on 2026-06-30 09:56

import django.contrib.postgres.fields
import netbox_backupjobs.models.backupjobs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0007_alter_backupjob_transformfulltosyntethic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupjob',
            name='TransformToSyntethicMonthly',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=netbox_backupjobs.models.backupjobs.default_synthetic_months),
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='TransformToSyntheticDays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=netbox_backupjobs.models.backupjobs.default_synthetic_days),
        ),
    ]
