# Generated by Django 6.0.4 on 2026-07-07 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0008_backupjob_scheduleperiodicallyfridayschema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='SchedulePeriodicallyHourOffsetInMin',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
    ]
