# Generated by Django 6.0.4 on 2026-06-30 12:07

import django.contrib.postgres.fields
import netbox_backupjobs.models.backupjobs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0008_alter_backupjob_transformtosyntethicmonthly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='EnableFullBackup',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='FullBackupDayNumberInMonth',
            field=models.CharField(default='first', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='FullBackupDayOfWeek',
            field=models.CharField(default='sunday', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='FullBackupDays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=netbox_backupjobs.models.backupjobs.default_full_backup_days),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='FullBackupMonths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=netbox_backupjobs.models.backupjobs.default_full_backup_months),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='FullBackupScheduleKind',
            field=models.CharField(default='daily', max_length=50),
        ),
    ]
