# Generated by Django 6.0.4 on 2026-07-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0009_backupjob_scheduleperiodicallyhouroffsetinmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backupjob',
            old_name='TransformFullToSyntethic',
            new_name='TransformFullToSynthetic',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='TransformToSyntethicKind',
            new_name='TransformToSyntheticKind',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='TransformToSyntethicMonthly',
            new_name='TransformToSyntheticMonthly',
        ),
    ]
