# Generated by Django 6.0.4 on 2026-06-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0009_backupjob_enablefullbackup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='target',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
