# Generated by Django 6.0.4 on 2026-06-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0010_backupjob_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='EnableGFS',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='MonthlyEnabled',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='MonthlyKeepBackupsFor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='MonthlyKeepBackupsWeekOfMonth',
            field=models.CharField(default='first', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='WeeklyEnabled',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='WeeklyKeepBackupsFor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='WeeklyKeepBackupsOnDayOfWeek',
            field=models.CharField(default='sunday', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='YearlyEnabled',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='YearlyKeepBackupsFor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='YearlyKeepBackupsOnMonthOfYear',
            field=models.CharField(default='january', max_length=50),
        ),
    ]
