# Generated by Django 6.0.4 on 2026-06-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0011_backupjob_enablegfs_backupjob_monthlyenabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupjob',
            name='MonthlyKeepBackupsFor',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='WeeklyKeepBackupsFor',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='YearlyKeepBackupsFor',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
