# Generated by Django 6.0.4 on 2026-07-07 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0012_alter_backupjob_scheduleperiodicallyhouroffsetinmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupjob',
            name='RetainCycles',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='RetainDaysToKeep',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='RetainDaysToKeepDeletedVmData',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
