# Generated by Django 6.0.4 on 2026-07-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0012_alter_backupjob_monthlykeepbackupsfor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='platform',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
