# Generated by Django 6.0.4 on 2026-07-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0013_alter_backupjob_retaincycles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupjob',
            name='SchedulePeriodicallyEvery',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
