# Generated by Django 6.0.4 on 2026-07-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0013_backupjob_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='job_creation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
