# Generated by Django 6.0.4 on 2026-07-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0014_backupjob_job_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupjob',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
