# Generated by Django 6.0.4 on 2026-07-09 08:49

import django.core.validators
import django.db.models.functions.text
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('netbox_backupjobs', '0014_alter_backupjob_scheduleperiodicallyevery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backupjob',
            old_name='AfterJobEnabled',
            new_name='after_job_enabled',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='AfterJobName',
            new_name='after_job_name',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='Algorithm',
            new_name='algorithm',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='EnableDeduplication',
            new_name='enable_deduplication',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='EnableDeletedVmDataRetention',
            new_name='enable_deleted_vm_data_retention',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='EnableFullBackup',
            new_name='enable_full_backup',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='EnableGFS',
            new_name='enable_gfs',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='FullBackupDayNumberInMonth',
            new_name='full_backup_day_number_in_month',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='FullBackupDayOfWeek',
            new_name='full_backup_day_of_week',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='FullBackupDays',
            new_name='full_backup_days',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='FullBackupMonths',
            new_name='full_backup_months',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='FullBackupScheduleKind',
            new_name='full_backup_schedule_kind',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='LastBackupEndTime',
            new_name='last_backup_end_time',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='LastBackupResult',
            new_name='last_backup_result',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='MonthlyEnabled',
            new_name='monthly_enabled',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='MonthlyKeepBackupsFor',
            new_name='monthly_keep_backups_for',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='MonthlyKeepBackupsWeekOfMonth',
            new_name='monthly_keep_backups_week_of_month',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='RetainCycles',
            new_name='retain_cycles',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='RetainDaysToKeep',
            new_name='retain_days_to_keep',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='RetainDaysToKeepDeletedVmData',
            new_name='retain_days_to_keep_deleted_vm_data',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='RunAutomatically',
            new_name='run_automatically',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='ScheduleDailyDays',
            new_name='schedule_daily_days',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='ScheduleDailyEnabled',
            new_name='schedule_daily_enabled',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='ScheduleDailyKind',
            new_name='schedule_daily_kind',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='ScheduleDailyTime',
            new_name='schedule_daily_time',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='ScheduleMonthlyDayNumberInMonth',
            new_name='schedule_monthly_day_number_in_month',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='ScheduleMonthlyDayOfMonth',
            new_name='schedule_monthly_day_of_month',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='ScheduleMonthlyDayOfWeek',
            new_name='schedule_monthly_day_of_week',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='ScheduleMonthlyEnabled',
            new_name='schedule_monthly_enabled',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='ScheduleMonthlyMonths',
            new_name='schedule_monthly_months',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='ScheduleMonthlyTime',
            new_name='schedule_monthly_time',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='SchedulePeriodicallyEnabled',
            new_name='schedule_periodically_enabled',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='SchedulePeriodicallyEvery',
            new_name='schedule_periodically_every',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='SchedulePeriodicallyFridaySchema',
            new_name='schedule_periodically_friday_schema',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='SchedulePeriodicallyHourOffsetInMin',
            new_name='schedule_periodically_hour_offset_in_min',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='SchedulePeriodicallyMondaySchema',
            new_name='schedule_periodically_monday_schema',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='SchedulePeriodicallySaturdaySchema',
            new_name='schedule_periodically_saturday_schema',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='SchedulePeriodicallySundaySchema',
            new_name='schedule_periodically_sunday_schema',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='SchedulePeriodicallyThursdaySchema',
            new_name='schedule_periodically_thursday_schema',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='SchedulePeriodicallyTuesdaySchema',
            new_name='schedule_periodically_tuesday_schema',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='SchedulePeriodicallyUnit',
            new_name='schedule_periodically_unit',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='SchedulePeriodicallyWednesdaySchema',
            new_name='schedule_periodically_wednesday_schema',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='StorageEncryptionEnabled',
            new_name='storage_encryption_enabled',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='SyntheticFullDayNumberInMonth',
            new_name='synthetic_full_day_number_in_month',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='SyntheticFullDayOfWeek',
            new_name='synthetic_full_day_of_week',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='TransformFullToSynthetic',
            new_name='transform_full_to_synthetic',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='TransformToSyntheticDays',
            new_name='transform_to_synthetic_days',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='TransformToSyntheticFull',
            new_name='transform_to_synthetic_full',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='TransformToSyntheticKind',
            new_name='transform_to_synthetic_kind',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='TransformToSyntheticMonthly',
            new_name='transform_to_synthetic_monthly',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='WeeklyEnabled',
            new_name='weekly_enabled',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='WeeklyKeepBackupsFor',
            new_name='weekly_keep_backups_for',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='WeeklyKeepBackupsOnDayOfWeek',
            new_name='weekly_keep_backups_on_day_of_week',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='YearlyEnabled',
            new_name='yearly_enabled',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='YearlyKeepBackupsFor',
            new_name='yearly_keep_backups_for',
        ),
        migrations.RenameField(
            model_name='backupjob',
            old_name='YearlyKeepBackupsOnMonthOfYear',
            new_name='yearly_keep_backups_on_month_of_year',
        ),
        migrations.CreateModel(
            name='BackupCopyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('jobtype', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='enabled', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('job_creation_time', models.DateTimeField(blank=True, null=True)),
                ('last_backup_result', models.CharField(blank=True, max_length=50)),
                ('retain_days_to_keep', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('target', models.CharField(blank=True, max_length=255)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'BackupCopyJob',
                'verbose_name_plural': 'Veeam BackupCopyJobs',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='netbox_backupjobs_backupcopyjob_unique_name', violation_error_message="The BackupCopyJob 'Name' must be unique.")],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
