# Generated by Django 6.0.4 on 2026-07-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0015_rename_afterjobenabled_backupjob_after_job_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupcopyjob',
            name='backup_jobs',
            field=models.ManyToManyField(blank=True, related_name='copy_jobs', to='netbox_backupjobs.backupjob'),
        ),
    ]
