# Generated by Django 6.0.4 on 2026-07-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0015_alter_backupjob_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupjob',
            name='RetainCycles',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='RetainDaysToKeep',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='RetainDaysToKeepDeletedVmData',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='comments',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='target',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
