# Generated by Django 6.0.4 on 2026-07-09 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0016_backupcopyjob_backup_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupcopyjob',
            name='data_transfer_mode',
            field=models.CharField(default='direct', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='enable_deduplication',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='enable_deleted_vm_data_retention',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='enable_gfs',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='mode',
            field=models.CharField(default='immediate', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='monthly_enabled',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='monthly_keep_backups_for',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='monthly_keep_backups_week_of_month',
            field=models.CharField(default='first', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='retain_days_to_keep_deleted_vm_data',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='storage_encryption_enabled',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='transaction_log_copy_enabled',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='weekly_enabled',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='weekly_keep_backups_for',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='weekly_keep_backups_on_day_of_week',
            field=models.CharField(default='sunday', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='yearly_enabled',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='yearly_keep_backups_for',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='yearly_keep_backups_on_month_of_year',
            field=models.CharField(default='january', max_length=50),
        ),
    ]
