# Generated by Django 6.0.4 on 2026-07-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0016_alter_backupjob_retaincycles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='jobtype',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
