# Generated by Django 6.0.4 on 2026-07-09 12:41

import django.contrib.postgres.fields
import django.core.validators
import netbox_backupjobs.models.backupcopyjobs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0017_backupcopyjob_data_transfer_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupcopyjob',
            name='transfer_window',
            field=models.CharField(default='continuously', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='transfer_window_friday_schema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupcopyjobs.default_transfer_window_all_hours),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='transfer_window_monday_schema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupcopyjobs.default_transfer_window_all_hours),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='transfer_window_saturday_schema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupcopyjobs.default_transfer_window_all_hours),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='transfer_window_sunday_schema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupcopyjobs.default_transfer_window_all_hours),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='transfer_window_thursday_schema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupcopyjobs.default_transfer_window_all_hours),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='transfer_window_tuesday_schema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupcopyjobs.default_transfer_window_all_hours),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='transfer_window_wednesday_schema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupcopyjobs.default_transfer_window_all_hours),
        ),
        migrations.AlterField(
            model_name='backupcopyjob',
            name='retain_days_to_keep',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
