# Generated by Django 6.0.4 on 2026-07-09 14:16

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import netbox_backupjobs.models.backupcopyjobs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_backupjobs', '0018_backupcopyjob_transfer_window_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupcopyjob',
            name='after_job_enabled',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='after_job_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preceding_jobs', to='netbox_backupjobs.backupcopyjob'),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='run_automatically',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_daily_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=netbox_backupjobs.models.backupcopyjobs.default_schedule_daily_days),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_daily_enabled',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_daily_kind',
            field=models.CharField(blank=True, default='everyday', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_daily_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_monthly_day_number_in_month',
            field=models.CharField(blank=True, default='first', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_monthly_day_of_month',
            field=models.CharField(blank=True, default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_monthly_day_of_week',
            field=models.CharField(blank=True, default='saturday', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_monthly_enabled',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_monthly_months',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=netbox_backupjobs.models.backupcopyjobs.default_schedule_monthly_months),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_monthly_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_periodically_enabled',
            field=models.CharField(default='false', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_periodically_every',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_periodically_friday_schema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupcopyjobs.default_transfer_window_all_hours),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_periodically_hour_offset_in_min',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_periodically_monday_schema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupcopyjobs.default_transfer_window_all_hours),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_periodically_saturday_schema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupcopyjobs.default_transfer_window_all_hours),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_periodically_sunday_schema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupcopyjobs.default_transfer_window_all_hours),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_periodically_thursday_schema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupcopyjobs.default_transfer_window_all_hours),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_periodically_tuesday_schema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupcopyjobs.default_transfer_window_all_hours),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_periodically_unit',
            field=models.CharField(blank=True, default='hours', max_length=50),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='schedule_periodically_wednesday_schema',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=netbox_backupjobs.models.backupcopyjobs.default_transfer_window_all_hours),
        ),
    ]
