# Generated by Django 6.0.4 on 2026-07-10 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0089_default_ordering_indexes'),
        ('netbox_backupjobs', '0019_backupcopyjob_after_job_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupcopyjob',
            name='backup_server_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_copy_jobs', to='ipam.ipaddress'),
        ),
        migrations.AddField(
            model_name='backupcopyjob',
            name='backup_server_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
